/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import audio.AePlayWave;
import audio.PlayAudio;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class JuegoGato1 extends javax.swing.JFrame {
    public int turno=1;
    public int total=0;
    public int []tiros= new int[9];
    public JButton[] imagenes= new JButton[9];
    /**
     * Creates new form JuegoGato1
     */
    public JuegoGato1() {
        initComponents();
        imagenes[0]= btnImagen1;
        imagenes[1]= btnImagen2;
        imagenes[2]= btnImagen3;
        imagenes[3]= btnImagen4;
        imagenes[4]= btnImagen5;
        imagenes[5]= btnImagen6;
        imagenes[6]= btnImagen7;
        imagenes[7]= btnImagen8;
        imagenes[8]= btnImagen9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnImagen1 = new javax.swing.JButton();
        btnImagen2 = new javax.swing.JButton();
        btnImagen4 = new javax.swing.JButton();
        btnImagen3 = new javax.swing.JButton();
        btnImagen5 = new javax.swing.JButton();
        btnImagen6 = new javax.swing.JButton();
        btnImagen7 = new javax.swing.JButton();
        btnImagen8 = new javax.swing.JButton();
        btnImagen9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vineta BT", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.png"))); // NOI18N
        jLabel1.setText("PLAY CAT");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        btnImagen1.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen1MouseClicked(evt);
            }
        });
        btnImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen1ActionPerformed(evt);
            }
        });
        btnImagen1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnImagen1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnImagen1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnImagen1KeyTyped(evt);
            }
        });

        btnImagen2.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen2MouseClicked(evt);
            }
        });
        btnImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen2ActionPerformed(evt);
            }
        });

        btnImagen4.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen4MouseClicked(evt);
            }
        });
        btnImagen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen4ActionPerformed(evt);
            }
        });

        btnImagen3.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen3MouseClicked(evt);
            }
        });
        btnImagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen3ActionPerformed(evt);
            }
        });

        btnImagen5.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen5MouseClicked(evt);
            }
        });
        btnImagen5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen5ActionPerformed(evt);
            }
        });

        btnImagen6.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen6MouseClicked(evt);
            }
        });
        btnImagen6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen6ActionPerformed(evt);
            }
        });

        btnImagen7.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen7MouseClicked(evt);
            }
        });
        btnImagen7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen7ActionPerformed(evt);
            }
        });

        btnImagen8.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen8MouseClicked(evt);
            }
        });
        btnImagen8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen8ActionPerformed(evt);
            }
        });

        btnImagen9.setBackground(new java.awt.Color(255, 204, 204));
        btnImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cattt.jpg"))); // NOI18N
        btnImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagen9MouseClicked(evt);
            }
        });
        btnImagen9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagen9ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));

        jLabel3.setFont(new java.awt.Font("Stylus BT", 0, 11)); // NOI18N
        jLabel3.setText("Jugador 1:");

        txtJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Stylus BT", 0, 11)); // NOI18N
        jLabel4.setText("Jugador2:");

        txtJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJugador2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        btnInicio.setBackground(new java.awt.Color(0, 153, 153));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 102, 102));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/START1.png"))); // NOI18N
        btnInicio.setText("START");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInicio))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInicio))
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton1.setText("REINICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnImagen1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnImagen2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImagen7)
                            .addComponent(btnImagen8)
                            .addComponent(btnImagen9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(839, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Vineta BT", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.png"))); // NOI18N
        jLabel2.setText("Juego del Gato");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImagen6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen6ActionPerformed
     try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen6ActionPerformed

    private void txtJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador1ActionPerformed
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador1ActionPerformed

    private void txtJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador2ActionPerformed

    private void btnImagen9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen9ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnImagen9ActionPerformed

    private void btnImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen1ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen1ActionPerformed

    private void btnImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen2ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen2ActionPerformed

    private void btnImagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen3ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen3ActionPerformed

    private void btnImagen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen4ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen4ActionPerformed

    private void btnImagen5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen5ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen5ActionPerformed

    private void btnImagen7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen7ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen7ActionPerformed

    private void btnImagen8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagen8ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Audio.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen8ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Music.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        String jugador= JOptionPane.showInputDialog("Dame el nombre del jugador 1");
        txtJugador1.setText(jugador);
        
        JOptionPane.showMessageDialog(null, "Bienvenid@: " + txtJugador1.getText() +
                                            "\n suerte!!!!" );
        
        jugador= JOptionPane.showInputDialog("Dame el nombre del jugador 2");
        txtJugador2.setText(jugador);
        
        JOptionPane.showMessageDialog(null, "Bienvenid@: " + txtJugador2.getText() +
                                            "\nsuerte!!!!" );
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnImagen1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnImagen1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen1KeyPressed

    private void btnImagen1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnImagen1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen1KeyReleased

    private void btnImagen1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnImagen1KeyTyped
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen1KeyTyped

    private void btnImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen1MouseClicked
        ponerImagen(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        turno=1;
        total=0;//numero de tiros realizados
        for(int i=0; i<9; i++){
            tiros[i]=0;
        }
        for(int i=0; i<9; i++){
            imagenes[i].setIcon(new ImageIcon(getClass().getResource("/imagenes/cattt.jpg")));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen2MouseClicked
        ponerImagen(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen2MouseClicked

    private void btnImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen3MouseClicked
        ponerImagen(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen3MouseClicked

    private void btnImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen4MouseClicked
        ponerImagen(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen4MouseClicked

    private void btnImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen5MouseClicked
        ponerImagen(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen5MouseClicked

    private void btnImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen6MouseClicked
        ponerImagen(5);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen6MouseClicked

    private void btnImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen7MouseClicked
        ponerImagen(6);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen7MouseClicked

    private void btnImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen8MouseClicked
        ponerImagen(7);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen8MouseClicked

    private void btnImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagen9MouseClicked
        ponerImagen(8);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImagen9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

     private void ponerImagen(int pos){
        if (tiros[pos] == 0) {
            if (turno == 1) {
                imagenes[pos].setActionCommand("X");
                imagenes[pos].setIcon(new ImageIcon(getClass().getResource("/imagenes/equis.png")));
                tiros[pos]= turno;
                turno = 2;
            } else {
                imagenes[pos].setActionCommand("O");
                imagenes[pos].setIcon(new ImageIcon(getClass().getResource("/imagenes/cero.png")));
                tiros[pos]= turno;
                turno = 1;
            }
           
        }
        total++;
            String ganador;
            ganador=verificar();
            if(ganador!=null){
                if(turno==1){
                  JOptionPane.showMessageDialog(null, "EL CAMPEON  HA SIDO !!" + ganador + "\n Jugador:" + txtJugador2.getText());
                  try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Applause.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
                }else{
                   JOptionPane.showMessageDialog(null,"EL CAMPEON  HA SIDO !!" + ganador + "\n Jugador:" + txtJugador1.getText());
                   try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Applause.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
            }else{
                if(total==9){
                    JOptionPane.showMessageDialog(null, "Hay un empate en el juego");
                }
            }
    }
    private String verificar(){
        if(imagenes[0].getActionCommand().equals("X")&&
                imagenes[0].getActionCommand().equals(imagenes[1].getActionCommand())
                &&imagenes[0].getActionCommand().equals(imagenes[2].getActionCommand())){
            return imagenes[0].getActionCommand();
        }
         if(imagenes[3].getActionCommand().equals("X")&&
                imagenes[3].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[3].getActionCommand().equals(imagenes[5].getActionCommand())){
            return imagenes[3].getActionCommand();
        }
          if(imagenes[6].getActionCommand().equals("X")&&
                imagenes[6].getActionCommand().equals(imagenes[7].getActionCommand())
                &&imagenes[6].getActionCommand().equals(imagenes[8].getActionCommand())){
            return imagenes[6].getActionCommand();
        }//comparacion de columnas
           if(imagenes[0].getActionCommand().equals("X")&&
                imagenes[0].getActionCommand().equals(imagenes[3].getActionCommand())
                &&imagenes[0].getActionCommand().equals(imagenes[6].getActionCommand())){
            return imagenes[0].getActionCommand();
        }
            if(imagenes[1].getActionCommand().equals("X")&&
                imagenes[1].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[1].getActionCommand().equals(imagenes[7].getActionCommand())){
            return imagenes[1].getActionCommand();
        }
             if(imagenes[2].getActionCommand().equals("X")&&
                imagenes[2].getActionCommand().equals(imagenes[5].getActionCommand())
                &&imagenes[2].getActionCommand().equals(imagenes[8].getActionCommand())){
            return imagenes[2].getActionCommand();
        }
         if(imagenes[0].getActionCommand().equals("X")&&
                imagenes[0].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[0].getActionCommand().equals(imagenes[8].getActionCommand())){
            return imagenes[0].getActionCommand();
        }
         if(imagenes[2].getActionCommand().equals("X")&&
                imagenes[2].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[2].getActionCommand().equals(imagenes[6].getActionCommand())){
            return imagenes[2].getActionCommand();
        }
        
         //Turno de "O"
         
          if(imagenes[0].getActionCommand().equals("O")&&
                imagenes[0].getActionCommand().equals(imagenes[1].getActionCommand())
                &&imagenes[0].getActionCommand().equals(imagenes[2].getActionCommand())){
            return imagenes[0].getActionCommand();
        }
         if(imagenes[3].getActionCommand().equals("O")&&
                imagenes[3].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[3].getActionCommand().equals(imagenes[5].getActionCommand())){
            return imagenes[3].getActionCommand();
        }
          if(imagenes[6].getActionCommand().equals("O")&&
                imagenes[6].getActionCommand().equals(imagenes[7].getActionCommand())
                &&imagenes[6].getActionCommand().equals(imagenes[8].getActionCommand())){
            return imagenes[6].getActionCommand();
        }//comparacion de columnas
           if(imagenes[0].getActionCommand().equals("O")&&
                imagenes[0].getActionCommand().equals(imagenes[3].getActionCommand())
                &&imagenes[0].getActionCommand().equals(imagenes[6].getActionCommand())){
            return imagenes[0].getActionCommand();
        }
            if(imagenes[1].getActionCommand().equals("O")&&
                imagenes[1].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[1].getActionCommand().equals(imagenes[7].getActionCommand())){
            return imagenes[1].getActionCommand();
        }
             if(imagenes[2].getActionCommand().equals("O")&&
                imagenes[2].getActionCommand().equals(imagenes[5].getActionCommand())
                &&imagenes[2].getActionCommand().equals(imagenes[8].getActionCommand())){
            return imagenes[2].getActionCommand();
        }
         if(imagenes[0].getActionCommand().equals("O")&&
                imagenes[0].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[0].getActionCommand().equals(imagenes[8].getActionCommand())){
            return imagenes[0].getActionCommand();
        }
         if(imagenes[2].getActionCommand().equals("O")&&
                imagenes[2].getActionCommand().equals(imagenes[4].getActionCommand())
                &&imagenes[2].getActionCommand().equals(imagenes[6].getActionCommand())){
            return imagenes[2].getActionCommand();
        }
       return null; 
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGato1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoGato1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagen1;
    private javax.swing.JButton btnImagen2;
    private javax.swing.JButton btnImagen3;
    private javax.swing.JButton btnImagen4;
    private javax.swing.JButton btnImagen5;
    private javax.swing.JButton btnImagen6;
    private javax.swing.JButton btnImagen7;
    private javax.swing.JButton btnImagen8;
    private javax.swing.JButton btnImagen9;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
